name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  history:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: denolib/setup-deno@master
        with:
          deno-version: v1.39.1
      - run: deno test history.test.ts
